# This workflow will build a gopy project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Gopy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install linux deps
        run: |
          sudo apt-get update
          sudo apt-get -y install libvips-dev libjpeg-turbo8-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install pybindgen
        run: |
          python3 -m pip install pybindgen
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/go-python/gopy@latest

      - name: Build
        run: |
          cd src/pkg/client
          gopy pkg -author="Photoroom" -email="team@photoroom.com" -url="" -name="datago" -version="0.99" .
          ls datago/*
